name: activate_gtp_stp_v81  # this you wont see anywhere by what I know today
label: v8.1 Activate GTP and SCTP logging   # this is left column "Label" under "Metadata Files" when importnmg a repo
description: Activation of GTP and SCTP capabilities # this is the description beside the label (right column)
type: panos
extends:

labels:
  service_type: mobile_panos

variables:
  - name: PLACEHOLDER
    description: Variable Placeholder
    default: Ignore
    type_hint: text


snippets:
  - name: set_log_quotas
    xpath: /config/devices/entry[@name='localhost.localdomain']/deviceconfig/setting/management/quota-settings
    file: quota-settings.xml
  - name: activate_gtp_sctp
    xpath: /config/devices/entry[@name='localhost.localdomain']/deviceconfig/setting
    file: activate_gtp_sctp.xml
